name: Main CI

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn

      # Build and deploy static-blog-example to Github Pages
      - run: yarn workspace @pwrc/static-blog-example build
        env:
          BASE_PATH: "/pwrc-react"
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/static-blog-example/public

      # Build and deploy static-blog-example and ecom-example to Vercel
      - run: yarn workspace @pwrc/static-blog-example clean
      - run: yarn workspace @pwrc/static-blog-example build
        env:
          BASE_PATH: "/examples/static-blog-example"
      - run: yarn workspace @pwrc/ecom-example build
        env:
          BASE_PATH: "/examples/ecom-example"
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./
          alias-domains: |
            pr-{{PR_NUMBER}}.pwrc-react.vercel.app
