name: PR CI

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn

  build-static-blog-example:
    needs: [install]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - run: yarn workspace @pwrc/static-blog-example build
        env:
          BASE_PATH: "/pwrc-react"

  build-ecom-example:
    needs: [install]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - run: yarn workspace @pwrc/ecom-example build
        env:
          BASE_PATH: "/pwrc-react"

  deploy-to-vercel:
    needs: [build-static-blog-example, build-ecom-example]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCELPROJECT_ID}}
          working-directory: ./
          alias-domains: |
            pr-{{PR_NUMBER}}.pwrc-react.vercel.app
