name: PR CI

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

  build-vercel-blog-example:
    runs-on: ubuntu-latest

    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn workspace @pwrc/static-blog-example build
        env:
          BASE_PATH: "/examples/static-blog-example"

      - uses: actions/cache@v2
        with:
          path: "./examples/static-blog-example"
          key: ${{ runner.os }}-vercel-blog-example-${{ github.sha }}

  build-vercel-ecom-example:
    runs-on: ubuntu-latest

    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn workspace @pwrc/ecom-example build
        env:
          BASE_PATH: "/examples/ecom-example"

      - uses: actions/cache@v2
        with:
          path: "./examples/ecom-example"
          key: ${{ runner.os }}-vercel-ecom-example-${{ github.sha }}

  build-docs:
    runs-on: ubuntu-latest

    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn workspace @pwrc/docs build
        env:
          FAUNA_PUBLIC_KEY: ${{ secrets.FAUNA_PUBLIC_KEY }}

      - uses: actions/cache@v2
        with:
          path: "./docs"
          key: ${{ runner.os }}-docs-${{ github.sha }}

  vercel-deploy:
    runs-on: ubuntu-latest

    needs:
      [
        install,
        build-vercel-blog-example,
        build-vercel-ecom-example,
        build-docs,
      ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "./examples/static-blog-example"
          key: ${{ runner.os }}-vercel-blog-example-${{ github.sha }}

      - uses: actions/cache@v2
        with:
          path: "./examples/ecom-example"
          key: ${{ runner.os }}-vercel-ecom-example-${{ github.sha }}

      - uses: actions/cache@v2
        with:
          path: "./docs"
          key: ${{ runner.os }}-docs-${{ github.sha }}

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./
